export const ADD_USER = 'ADD_USER'

export const ADD_TRAINING = 'ADD_TRAINING'
export const REMOVE_TRAINING = 'REMOVE_TRAINING'
export const UPDATE_TRAINING = 'UPDATE_TRAINING'
export const REQUEST_EXERCISEBLOCKS = 'REQUEST_EXERCISEBLOCKS'
export const RECEIVE_EXERCISEBLOCKS = 'RECEIVE_EXERCISEBLOCKS'

export const FETCH = 'FETCH'
